### PR TITLE
Fix auto import

### PR DESCRIPTION
**Pull request by tdurieux**
Normally the tests are passing but I am not sure about `) && !(role.equals(CtRole.DECLARING_TYPE) && reference.getParent() instanceof CtTypeReference)`

### CODE REVIEW

**Comment by pvojtechovsky** [comment]
LGTM, many thanks for helping me with that!

> but I am not sure about ) && !(role.equals(CtRole.DECLARING_TYPE) && reference.getParent() instanceof CtTypeReference)

I need to debug situation when it occurs. The context is not clear to me yet..

**Comment by tdurieux** [comment]
I can give you some explanation.

In this file:   `spoon.test.imports.testclasses.ClientClass` (https://github.com/pvojtechovsky/spoon/blob/refImports/src/test/java/spoon/test/imports/testclasses/ClientClass.java#L6), there is a field of the type `spoon.test.imports.testclasses.internal.ChildClass.InnerClassProtected` which extends `spoon.test.imports.testclasses.internal.SuperClass` (https://github.com/pvojtechovsky/spoon/blob/refImports/src/test/java/spoon/test/imports/testclasses/internal/SuperClass.java).
The import scanner detected that `spoon.test.imports.testclasses.internal.SuperClass` should be imported in `spoon.test.imports.testclasses.ClientClass` but it is wrong and also produces a compilation error since `spoon.test.imports.testclasses.internal.SuperClass` is package protected.

my "fix" is to exclude all the references that have a reference as a parent and that have declaring type role.
I think that this rule should be implemented somewhere else, but I did not find it, sorry.

**Comment by pvojtechovsky** [comment]
>  && !(role.equals(CtRole.DECLARING_TYPE) && reference.getParent() instanceof CtTypeReference)

which test fails when that change is not applied?

**Comment by tdurieux** [comment]
this one spoon.test.imports.ImportTest#testImportOfAnInnerClassInASuperClassPackageAutoImport

**Comment by pvojtechovsky** [comment]
> my "fix" is to exclude all the references that have a reference as a parent and that have declaring type role.
I think that this rule should be implemented somewhere else, but I did not find it, sorry.

I moved the fix to AbstractCompilationUnitImportsProcessor.ScannerListener. I wonder whether it will pass all tests. I have feeling like some test case is missing which will make it failing ...

**Pull request merged**
